language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  
before_script:
  - composer self-update
  - composer install
  - composer update satooshi/php-coveralls --dev
  - mysql -e 'create database shop;'
  - mysql -e 'USE shop;'
  - mysql -e 'create table shop.products(
              products_id INT(7) AUTO_INCREMENT PRIMARY KEY,
              products_quantity INT(6) NOT NULL,
              products_model VARCHAR(36) NOT NULL
              ) ENGINE=InnoDB DEFAULT CHARSET=utf8;'
  - mysql -e 'INSERT INTO shop.products(products_id, products_quantity, products_model) VALUES("1000001", "31", "example1")'
  - mysql -e 'INSERT INTO shop.products(products_id, products_quantity, products_model) VALUES("1000002", "15", "example2")'
  
test:
  adapter: mysql2
  database: shop
  username: root
  encoding: utf8

script:
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls
 - php vendor/bin/coveralls -v
