language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  
before_script:
  - mysql -e 'create database myapp_test;'
  
test:
  adapter: mysql2
  database: shop
  username: root
  encoding: utf8

script: phpunit