language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  
before_script:
  - mysql -e 'create database shop;'
  - mysql -e 'create table products(
              products_id INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
              products_quantity INT(6) NOT NULL,
              products_model VARCHAR(30) NOT NULL,
              );'
  - mysql -e 'INSERT INTO products (products_id, products_quantity, products_model) VALUES (1000001, 31, example1);'
  - mysql -e 'INSERT INTO products (products_id, products_quantity, products_model) VALUES (1000002, 15, example2);'
  
test:
  adapter: mysql2
  database: shop
  username: root
  encoding: utf8

script: phpunit
